# website title
title: Alexandre Plateau
# short description for the website
description: Autodidact C++/Python developper
# avatar to be used on the website
logo: https://avatars2.githubusercontent.com/u/10694085?s=460&v=4

google_analytics: NOCODE
# disable download button
show_downloads: false
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
  - jemoji
