# website title
title: SuperFola | Alexandre Plateau
# short description for the website
description: I am a french programmer, and here is my CV
# avatar to be used on the website
avatar: 
google_analytics: NOCODE
# disable download button
show_downloads: false
theme: jekyll-theme-dinky

gems:
  - jekyll-mentions
  - jemoji
